#!/usr/bin/env node
/**
 * summary-comment.js
 *
 * Posts or updates a single “GUI Test Review” comment on a PR.
 * The comment aggregates:
 *   • Playwright metrics
 *   • Prettier + ESLint summaries
 *   • Flow-diagram / dashboard link
 *   • Checklist
 */

const fs = require('fs');
const path = require('path');
const { Octokit } = require('@octokit/core');

/* ─── helpers ─────────────────────────────────────────────────────── */
const readJSON = (fp, fallback = {}) => {
  try { return JSON.parse(fs.readFileSync(fp, 'utf8')); }
  catch { return fallback; }
};
const icon = (ok, warn = false) => (ok ? '✅' : warn ? '⚠️' : '❌');

/* ─── GitHub context ──────────────────────────────────────────────── */
const token = process.env.GITHUB_TOKEN;
if (!token) { console.error('GITHUB_TOKEN missing'); process.exit(1); }

const event = JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8'));
if (!event.pull_request) { console.log('Not a PR event; skipping comment.'); process.exit(0); }

const owner = event.repository.owner.login;
const repo  = event.repository.name;
const pr    = event.number;

/* ─── load artefact summaries ─────────────────────────────────────── */
const ART = 'artifacts';
const play   = readJSON(path.join(ART, 'playwright-summary.json'));
const eslint = readJSON(path.join(ART, 'eslint-summary.json'));
const prett  = readJSON(path.join(ART, 'prettier-summary.json'));
const checklist = readJSON(path.join(ART, 'checklist.json')).md || '';

/* URL to the live dashboard, injected by the workflow */
const webUrl = process.env.WEB_REPORT_URL;

/* ─── compose comment body ────────────────────────────────────────── */
const body = `
# 🔍 GUI Test Review Report

## ✅ Test Execution Summary
| Metric | Value | Status |
| ------ | ----- | ------ |
| **Total Tests** | ${play.total   ?? 0} | |
| **Passed**      | ${play.passed  ?? 0} | ${icon((play.passed ?? 0) === (play.total ?? 0), (play.failed ?? 0) === 0)} |
| **Failed**      | ${play.failed  ?? 0} | ${icon((play.failed ?? 0) === 0)} |
| **Skipped**     | ${play.skipped ?? 0} | ${icon((play.skipped ?? 0) === 0, true)} |
| **Pass Rate**   | ${play.pass_rate ?? 0}% | ${icon((play.pass_rate ?? 0) >= 95, (play.pass_rate ?? 0) >= 80)} |
| **Duration**    | ${play.duration ?? 0} ms | |

---

## 🎨 Code Style (Prettier)
| Check | Result |
|-------|--------|
| **Style Issues** | ${prett.has_issues ? '❌ Found' : '✅ None'} |
| **Files Affected** | ${prett.files_with_issues ?? 0} |
| **Total Changes**  | ${prett.total_changes    ?? 0} |

---

## 📋 Code Quality (ESLint)
| Metric | Count | Status |
| ------ | ----- | ------- |
| **Files**    | ${eslint.total_files ?? 0} | |
| **Errors**   | ${eslint.errors      ?? 0} | ${icon((eslint.errors ?? 0) === 0)} |
| **Warnings** | ${eslint.warnings    ?? 0} | ${icon((eslint.warnings ?? 0) === 0, true)} |
| **Fixable**  | 🔴 ${eslint.fixable_errors ?? 0} / 🟡 ${eslint.fixable_warnings ?? 0} | |

**Top Rules:**  
${eslint.error_rules   ?? 'None'}  
${eslint.warning_rules ?? 'None'}

**Files Needing Attention:**  
${eslint.problematic_files ?? 'None'}

---

## 📊 Test Flow Diagram
${webUrl ? `👉 **[Open the full HTML dashboard ↗](${webUrl})**`
         : 'Flowchart is attached as workflow artefact.'}

---

## ✅ Checklist
${checklist}

---

_Automated comment generated by the GUI Test Review workflow._
`;

/* ─── create or update the sticky comment ─────────────────────────── */
const octokit = new Octokit({ auth: token });

(async () => {
  const { data: comments } = await octokit.request(
    'GET /repos/{owner}/{repo}/issues/{issue_number}/comments',
    { owner, repo, issue_number: pr }
  );

  const existing = comments.find(
    c => c.user.type === 'Bot' &&
         c.body.startsWith('# 🔍 GUI Test Review Report')
  );

  if (existing) {
    await octokit.request(
      'PATCH /repos/{owner}/{repo}/issues/comments/{comment_id}',
      { owner, repo, comment_id: existing.id, body }
    );
    console.log('🔄 Updated GUI-test summary comment.');
  } else {
    await octokit.request(
      'POST /repos/{owner}/{repo}/issues/{issue_number}/comments',
      { owner, repo, issue_number: pr, body }
    );
    console.log('💬 Created GUI-test summary comment.');
  }
})().catch(err => {
  console.error(err);
  process.exit(1);
});
