name: Post GitHub Pages Link in PR

on:
  pull_request:
    types: [opened, synchronize, reopened] # Triggers when a PR is opened, updated, or re-opened

jobs:
  comment_link:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # This permission is essential for the Action to post comments on PRs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Post GitHub Pages Link to PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            👋 Hello!

            Here's the link to our GitHub Pages site:
            [View Blank Page]({{ https://digitalproductinnovationanddevelopment.github.io/Code-Reviews-of-GUI-Tests/ }})

            This link will always show the latest version from our main branch.

          update-tag: 'github-pages-link-comment' # This ensures the comment gets updated on subsequent pushes, not duplicated
