name: Playwright Screenshot on PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Playwright screenshot script
        run: node scripts/screenshot.js

      - name: Comment PR with screenshots
        uses: opengisch/comment-pr-with-images@upload_only
        with:
          images: "tests_artifacts/**/*.png"
          upload_to: github_branch
          custom_attachment_msg: "Automated Playwright screenshots for this PR"
          edit_previous_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
