name: Playwright Screenshot on PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright screenshot script
        run: node scripts/screenshot.js

      - name: List screenshots folder (debug)
        run: ls -lR tests_artifacts

      - name: Comment PR with screenshots
        uses: opengisch/comment-pr-with-images@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          images: "tests_artifacts/**/*.png"
          upload_to: pr_comment
