name: GUI Screenshots in PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  capture-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Playwright
        run: npx playwright install chromium

      - name: Take screenshots
        run: node scripts/screenshot.js

      - name: Post images to PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: gui-screenshots
          message: |
            ## 🖼️ UI Screenshots
            ${{ steps.screenshots.outputs.images }}
