name: GUI Screenshots in PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  capture-screenshots:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright
        run: npx playwright install chromium

      - name: Capture and embed screenshots
        id: screenshots
        run: node scripts/screenshot.js
        
      - name: Post images to PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: gui-screenshots
          message: |
            ## 🖼️ Automated UI Preview
            ${{ steps.screenshots.outputs.images }}
